name: Generate Report

on:
  push:
    branches:
      - main
      - feature/package
  workflow_dispatch:
    inputs:
      url:
        description: "URL to generate a report for."
        required: true

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Install geckodriver
      run: |
        wget https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz
        tar -xvzf geckodriver-v0.30.0-linux64.tar.gz
        chmod +x geckodriver
        sudo mv geckodriver /usr/local/bin/

    - name: Get Clean URL name
      id: get-clean-url-name
      run: |
        echo "https://google.com" | sed 's/http:\/\///'
        echo "https://google.com" | sed 's/https:\/\///'

    - name: Generate Report -- Google
      if: ${{ github.event_name == 'push' }}
      run: |
        access-eval-generate-report \
          https://google.com \
          --output_dir https://google.com--report \
          --archive

    - name: Store Report -- Parametrized
      if: ${{ github.event_name == 'push' }}
      uses: actions/upload-artifact@v2
      with:
        name: https://google.com--report
        path: https://google.com--report.tar
    
    - name: Generate Report -- Parametrized
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        access-eval-generate-report \
          ${{ github.event.inputs.url }} \
          --output_dir ${{ github.event.inputs.url }}--report \
          --archive
    
    - name: Store Report -- Parametrized
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.inputs.url }}--report
        path: ${{ github.event.inputs.url }}--report.tar
